apiVersion: v2
name: guacamole
description: Helm chart for guacamole
version: 0.10.1
type: application

appVersion: 1.6.0

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: ~2
  - condition: postgresql.enabled
    name: cluster
    repository: https://cloudnative-pg.github.io/charts
    version: ~0.3.1
    alias: postgresql
