apiVersion: v2
name: guacamole
description: Helm chart for guacamole
version: 0.11.2
type: application

appVersion: 1.6.0

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: ~2
