apiVersion: v2
name: guacamole
description: Helm chart for guacamole
version: 0.6.2
type: application

appVersion: 1.5.5

dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.x.x
