apiVersion: v2
name: guacamole
description: Helm chart for guacamole
version: 0.9.5
type: application

appVersion: 1.6.0

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: ~2
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.x.x
