apiVersion: v2
name: guacamole
description: Helm chart for guacamole
version: 0.7.0
type: application

appVersion: 1.6.0

dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.x.x
