global:
  # Kubernetes secret for pulling images
  imagePullSecret: ~

# guacd
daemon:
  image: 
    repository: guacamole/guacd
    tag: ""
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75
    behavior: {}
      # scaleDown:
      #  stabilizationWindowSeconds: 300
      #  policies:
      #   - type: Pods
      #     value: 1
      #     periodSeconds: 180
      # scaleUp:
      #   stabilizationWindowSeconds: 300
      #   policies:
      #   - type: Pods
      #     value: 2
      #     periodSeconds: 60
  port: 4822
  
  service:
    port: 4822

# guacamole
portal:
  image:
    repository: reprostat/guacamole
    tag: github
    pullPolicy: Always
  replicas: 1
  resources:
    requests:
      memory: "1024Mi"
      cpu: "250m"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75
    behavior: {}
      # scaleDown:
      #  stabilizationWindowSeconds: 300
      #  policies:
      #   - type: Pods
      #     value: 1
      #     periodSeconds: 180
      # scaleUp:
      #   stabilizationWindowSeconds: 300
      #   policies:
      #   - type: Pods
      #     value: 2
      #     periodSeconds: 60
  port: 8080
  
  service:
    port: 8080
  
  ingress:
    enabled: true
    annotations: {}
    className: nginx
    host: guacamole.local
    tls:
      enabled: false
      secretName: guacamole-tls

# connections
database:
  type: ldap
  hostname: ldap.local
  port: 389
  encryptionMethod: starttls
  tlsSecretname: guacamole-tls
  bindSecret: guacamole-ldap
  maxSearchResults: 1000
  userBaseDN: ou=people,dc=example,dc=com
  usernameAttribute: uid
  memberAttribute: uniqueMember
  memberAttributeType: dn
  guacConfigBaseDN: ou=guacConfigs,ou=groups,dc=example,dc=com

hostAliases: []
