global:
  imagePullSecrets: []

# guacd
daemon:
  image: guacamole/guacd:1.5.5
  replicas: 1
  port: 4822
  
  service:
    port: 4822

# guacamole
portal:
  image: guacamole/guacamole:1.5.5
  replicas: 1
  port: 8080
  
  service:
    port: 8080
  
  ingress:
    enabled: true
    annotations: {}
    className: nginx
    host: guacamole.local
    tls:
      enabled: false
      secretName: guacamole-tls

# connections
database:
  type: ldap
  hostname: ldap.local
  port: 389
  encryptionMethod: starttls
  bindSecret: guacamole-ldap
  maxSearchResults: 1000
  userBaseDN: ou=people,dc=example,dc=com
  usernameAttribute: uid
  memberAttribute: uniqueMember
  memberAttributeType: dn
  guacConfigBaseDN: ou=guacConfigs,ou=groups,dc=example,dc=com
