apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guacamole.portal.name" . }}
spec:
  {{- if not .Values.portal.autoscaling.enabled }}
  replicas: {{ .Values.portal.replicas }}
  {{- end }}  
  selector:
    matchLabels:
      app: {{ include "guacamole.portal.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "guacamole.portal.name" . }}
    spec:
      serviceAccountName: {{ include "guacamole.portal.name" . }}
      nodeSelector:
        {{- toYaml .Values.portal.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.portal.tolerations | nindent 8 }}
        
      volumes:
      {{- if and (eq .Values.database.type "ldap") (eq .Values.database.encryptionMethod "starttls") }}
        - name: ldap-tls
          secret:
            secretName: {{ .Values.database.tlsSecretname }}
      {{- end }}
      {{- if .Values.portal.volumes }}
      {{ toYaml .Values.portal.volumes | nindent 6 }}
      {{- end }}
      
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      containers:
      - name: portal
        image: {{ .Values.portal.image.repository }}:{{ default .Chart.AppVersion .Values.portal.image.tag }}
        imagePullPolicy: {{ .Values.portal.image.pullPolicy | quote }}
        env:
        - name: GUACD_HOSTNAME
          value: daemon
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx2048m -Xss1024k -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

        {{- if eq .Values.database.type "postgres" }}
        - name: POSTGRESQL_HOSTNAME
          value: {{ .Values.database.hostname }}
        - name: POSTGRESQL_PORT
          value: {{ .Values.database.port | quote }}
        - name: POSTGRESQL_DATABASE
          value: {{ .Values.database.database }}
        - name: POSTGRESQL_USER
          value: {{ .Values.database.user }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "guacamole.password.secret" . }}
              key: {{ .Values.database.password.key }}
        - name: POSTGRESQL_AUTO_CREATE_ACCOUNTS
          value: "true"
        {{- end }}

        {{- if eq .Values.database.type "mysql" }}
        - name: MYSQL_HOSTNAME
          value: {{ .Values.database.hostname }}
        - name: MYSQL_PORT
          value: {{ .Values.database.port }}
        - name: MYSQL_DATABASE
          value: {{ .Values.database.database }}
        - name: MYSQL_USER
          value: {{ .Values.database.user }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "guacamole.password.secret" . }}
              key: {{ .Values.database.password.key }}
        - name: MYSQL_AUTO_CREATE_ACCOUNTS
          value: "true"
        {{- end }}

        {{- if eq .Values.database.type "ldap" }}
        - name: LDAP_HOSTNAME
          value: {{ .Values.database.hostname }}
        - name: LDAP_PORT
          value: {{ .Values.database.port | quote }}
        - name: LDAP_ENCRYPTION_METHOD
          value: {{ .Values.database.encryptionMethod }}
        - name: LDAP_SEARCH_BIND_DN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.bindSecret }}
              key: LDAP_bindDN
        - name: LDAP_SEARCH_BIND_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.bindSecret }}
              key: LDAP_bindPW
        - name: LDAP_MAX_SEARCH_RESULTS
          value: {{ .Values.database.maxSearchResults | quote  }}
        - name: LDAP_USER_BASE_DN
          value: {{ .Values.database.userBaseDN }}
        - name: LDAP_USERNAME_ATTRIBUTE
          value: {{ .Values.database.usernameAttribute }}
        - name: LDAP_MEMBER_ATTRIBUTE
          value: {{ .Values.database.memberAttribute }}
        - name: LDAP_MEMBER_ATTRIBUTE_TYPE
          value: {{ .Values.database.memberAttributeType }}
        - name: LDAP_CONFIG_BASE_DN
          value: {{ .Values.database.guacConfigBaseDN }}
        {{- if or (eq .Values.database.encryptionMethod "ssl") (eq .Values.database.encryptionMethod "starttls") }}
        - name: EXTRA_CACERT_ENABLED
          value: "true"
        - name: EXTRA_CACERT_SEARCH_PATH
          value: "/opt/guacamole/certs"
        {{- end }}          
        {{- end }}

        {{- if .Values.portal.env }}
        {{ toYaml .Values.portal.env | nindent 8 }}
        {{- end }}
        
        volumeMounts:
        {{- if and (eq .Values.database.type "ldap") (or (eq .Values.database.encryptionMethod "ssl") (eq .Values.database.encryptionMethod "starttls")) }}
          - name: ldap-tls
            mountPath: /opt/guacamole/certs/ldap-ca.crt
            subPath: ca.crt
            readOnly: true
        {{- end }}
        {{- if .Values.portal.volumeMounts }}
        {{ toYaml .Values.portal.volumeMounts | nindent 8 }}
        {{- end }}
          
        resources:
          {{- toYaml .Values.portal.resources | nindent 10 }}

        ports:
        - containerPort: {{ .Values.portal.port }}
          name: http
          protocol: TCP

      {{- if .Values.hostAliases }}
      hostAliases:
      {{ toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}      