{{ if .Values.portal.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:  
  name: {{ include "guacamole.portal.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/app-root: /guacamole
    {{ if .Values.portal.ingress.annotations }}          
    {{ toYaml .Values.portal.ingress.annotations | nindent 4 }}
    {{ end }}
spec:
  ingressClassName: {{ .Values.portal.ingress.className }}
  rules:
    - host: {{ .Values.portal.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: /            
            backend:
              service:
                name: {{ include "guacamole.portal.fullname" . }}
                port:
                  number: {{ .Values.portal.service.port }}
            

  {{ if .Values.portal.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.portal.ingress.host }}
      secretName: {{ .Values.portal.ingress.tls.secretName }}
  {{ end }}
{{ end }}