apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-portal" .Release.Name }}
  annotations:
  labels:
    app.kubernetes.io/component: {{ include "guacamole.portal.fullname" . }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/component: {{ include "guacamole.portal.fullname" . }}
  ports:
  - name: http
    port: {{ .Values.portal.service.port }}
    protocol: TCP
    targetPort: {{ .Values.portal.port }}