{{- if and (hasKey .Values.authentication "database") (eq .Values.authentication.database.type "postgres") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.database.fullname" . }}-superuser
  annotations:
  labels:
    app.kubernetes.io/component: {{ include "guacamole.database.fullname" . }}
    release: {{ .Release.Name }}
spec:
type: kubernetes.io/basic-auth
stringData:
  {{- if (.Values.authentication.database.postgresql.superuser).secret }}
  {{- $secret := .Values.authentication.database.postgresql.superuser.secret }}
  {{- $username := (lookup "v1" "Secret" .Release.Namespace $secret).data.username | b64dec }}
  {{- $password := (lookup "v1" "Secret" .Release.Namespace $secret).data.password | b64dec }}
  username: {{ $username }}
  password: {{ $password }}
  {{- else }}
  username: postgres
  password: {{ default (randAlphaNum 16) }}
  {{- end }}
{{- end }}    