{{- if and (hasKey .Values.authentication "database") (eq .Values.authentication.database.type "postgres") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "guacamole.database.fullname" . }}
{{- end}}