apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guacamole.daemon.name" . }}
spec:
  {{- if not .Values.daemon.autoscaling.enabled }}
  replicas: {{ .Values.daemon.replicas }}
  {{- end }}  
  selector:
    matchLabels:
      app: {{ include "guacamole.daemon.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "guacamole.daemon.name" . }}
    spec:
      serviceAccountName: {{ include "guacamole.daemon.name" . }}
      nodeSelector:
        {{- toYaml .Values.daemon.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.daemon.tolerations | nindent 8 }}
        
      volumes:
      {{ if .Values.daemon.volumes }}
      {{ toYaml .Values.daemon.volumes | nindent 6 }}
      {{ end }}

      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      containers:
      - name: daemon
        image: {{ .Values.daemon.image.reprository }}:{{ default .Chart.AppVersion .Values.daemon.image.tag }}
        imagePullPolicy: {{ .Values.daemon.image.pullPolicy | quote }}
        env:
        {{ if .Values.env }}
        {{ toYaml .Values.env | nindent 8 }}
        {{ end }}
        
        volumeMounts:
        {{ if .Values.daemon.volumeMounts }}
        {{ toYaml .Values.daemon.volumeMounts | nindent 8 }}
        {{ end }}
          
        resources:
          {{- toYaml .Values.daemon.resources | nindent 10 }}

        ports:
        - containerPort: {{ .Values.daemon.port }}
          name: daemon
          protocol: TCP

      {{ if .Values.hostAliases }}
      hostAliases:
      {{ toYaml .Values.hostAliases | nindent 8 }}
      {{ end }}      