{{- if .Values.daemon.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "guacamole.daemon.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "guacamole.daemon.name" . }}
  minReplicas: {{ .Values.daemon.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.daemon.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.daemon.autoscaling.metrics }}
    {{- toYaml . | nindent 4 }}
  {{- else }}
    {{- with .Values.daemon.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
    {{- with .Values.daemon.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
  {{- end }}
  {{- with .Values.daemon.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}