apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-deamon" .Release.Name }}
  annotations:
  labels:
    app.kubernetes.io/component: {{ include "guacamole.daemon.fullname" . }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/component: {{ include "guacamole.daemon.fullname" . }}
  ports:
  - name: daemon
    port: {{ .Values.daemon.service.port }}
    protocol: TCP
    targetPort: {{ .Values.daemon.port }}