apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ template "guacamole.daemon.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "guacamole.daemon.fullname" . }}
    release: {{ .Release.Name }}
spec:
  {{- if not .Values.daemon.autoscaling.enabled }}
  replicas: {{ .Values.daemon.replicas }}
  {{- end }}  
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ template "guacamole.daemon.fullname" . }}
  template:
    metadata:
      labels:  {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: {{ template "guacamole.daemon.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "guacamole.daemon.fullname" . }}
        
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30       
      containers:
        - name: daemon
          image: {{ .Values.daemon.image.repository }}:{{ default .Chart.AppVersion .Values.daemon.image.tag }}
          imagePullPolicy: {{ .Values.daemon.image.pullPolicy | quote }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
         
          resources:
            {{- toYaml .Values.daemon.resources | nindent 12 }}

          ports:
            - containerPort: {{ .Values.daemon.port }}
              name: daemon
              protocol: TCP

      {{- if .Values.hostAliases }}
      hostAliases:
      {{ toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}      